/*
* class File
*/


// properties ... seems File has no properties ...
//methods
public static StreamReader OpenText(string path)
public static StreamWriter CreateText(string path)
public static StreamWriter AppendText(string path)

public static void Copy(string sourceFileName, string destFileName)
public static void Copy(string sourceFileName, string destFileName, bool overwrite)

public static FileStream Create(string path)
public static FileStream Create(string path, int bufferSize)
public static FileStream Create(string path, int bufferSize, FileOptions options)
public static FileStream Create(string path, int bufferSize, FileOptions options, FileSecurity fileSecurity)

public static void Delete(string path)
public static void Decrypt(string path)
public static void Encrypt(string path)
public static bool Exists(string path)

public static FileStream Open(string path, FileMode mode)
public static FileStream Open(string path, FileMode mode, FileAccess access)
public static FileStream Open(string path, FileMode mode, FileAccess access, FileShare share)
public static void SetCreationTime(string path, DateTime creationTime)
public unsafe static void SetCreationTimeUtc(string path, DateTime creationTimeUtc)
public static DateTime GetCreationTime(string path)
public static DateTime GetCreationTimeUtc(string path)
public static void SetLastAccessTime(string path, DateTime lastAccessTime)
public unsafe static void SetLastAccessTimeUtc(string path, DateTime lastAccessTimeUtc)
public static DateTime GetLastAccessTime(string path)
public static DateTime GetLastAccessTimeUtc(string path)
public static void SetLastWriteTime(string path, DateTime lastWriteTime)
public unsafe static void SetLastWriteTimeUtc(string path, DateTime lastWriteTimeUtc)
public static DateTime GetLastWriteTime(string path)
public static DateTime GetLastWriteTimeUtc(string path)
public static FileAttributes GetAttributes(string path)
public static void SetAttributes(string path, FileAttributes fileAttributes)
public static FileSecurity GetAccessControl(string path)
public static FileSecurity GetAccessControl(string path, AccessControlSections includeSections)
public static void SetAccessControl(string path, FileSecurity fileSecurity)
public static FileStream OpenRead(string path)
public static FileStream OpenWrite(string path)
public static string ReadAllText(string path)
public static string ReadAllText(string path, Encoding encoding)
public static void WriteAllText(string path, string contents)
public static void WriteAllText(string path, string contents, Encoding encoding)
public static byte[] ReadAllBytes(string path)
public static void WriteAllBytes(string path, byte[] bytes)
public static string[] ReadAllLines(string path)
public static string[] ReadAllLines(string path, Encoding encoding)
public static IEnumerable<string> ReadLines(string path)
public static IEnumerable<string> ReadLines(string path, Encoding encoding)
public static void WriteAllLines(string path, string[] contents)
public static void WriteAllLines(string path, string[] contents, Encoding encoding)
public static void WriteAllLines(string path, IEnumerable<string> contents)
public static void WriteAllLines(string path, IEnumerable<string> contents, Encoding encoding)
public static void AppendAllText(string path, string contents)
public static void AppendAllText(string path, string contents, Encoding encoding)
public static void AppendAllLines(string path, IEnumerable<string> contents)
public static void AppendAllLines(string path, IEnumerable<string> contents, Encoding encoding)
public static void Move(string sourceFileName, string destFileName)
public static void Replace(string sourceFileName, string destinationFileName, string destinationBackupFileName)
public static void Replace(string sourceFileName, string destinationFileName, string destinationBackupFileName, bool ignoreMetadataErrors)
